version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: conf/Dockerfile
    container_name: laravel_php
    working_dir: /var/www/laravel
    user: "www-data"
    volumes:
      - ./src:/var/www/laravel
      - ./conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - php_logs:/var/log/php
    env_file:
      - .env
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/laravel
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
  php_logs:
  mysql_logs:
  nginx_logs:
